puts "Andrea Cremese, testting for trial application for Cyrus Innovation"
puts "March 2014 - see http://www.cyrusinnovation.com/code-test-ruby/ for the brief"
puts "This is a Gino production, che credevate o'duri \n"
puts "loading tests on the reader_file"
load "reader_file_spec.rb"
puts "loading tests on the runner_parsing"
load "run_parsing_spec.rb"
puts "\n\nThanks for your time!"
puts "Andrea Cremese, cremese@gmail.com, https://github.com/AndreaHK5\n\n" 